@hostname=localhost
@port=5116


POST http://{{hostname}}:{{port}}/GenerateRandomData
Content-Type: application/json
{
	"ItemLength": 1
}

###

GET http://{{hostname}}:{{port}}/GetToDoItems/50/1
Content-Type: application/json