# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostname=localhost
@port=5116
@host={{hostname}}:{{port}}
GET	http://{{host}}/

###

GET	http://{{host}}/1

###

POST http://{{host}}/
Content-Type: application/json

{
	 "Name": "test123",
   "IsComplete": false
}

###

PUT http://{{host}}/5
Content-Type: application/json

{
	 "Name": "pierwa",
   "IsComplete": false
}

###

DELETE http://{{host}}/4
Content-Type: application/json

###
